### ISSUE TITLE
Sales Tab becomes blank

### ISSUE THREAD

**Issue by vrajeshpatel4u** [stock2shop/magento2_module_webhook#1]
Hello, I have installed Magento 2.2.5 and install this shipping extension. Before install in Admin Panel Store --> Configuration --> Sales All tab display well, but after installing this extension sales tab becomes blank. I have used all commands listed in guidelines. Below I have attached screen shot. 
![after configuration settings stores magento admin](https://user-images.githubusercontent.com/40518060/44223426-370bdc00-a1a5-11e8-8448-ce598b97167c.png)

![log error](https://user-images.githubusercontent.com/40518060/44223727-0bd5bc80-a1a6-11e8-9fce-829d9d20562e.png)

**Comment by dmitry-fedyuk** [comment]
[How to diagnose Magento 2 errors](https://mage2.pro/t/topic/307)

**Comment by vrajeshpatel4u** [comment]
I have checked all options, not find any error.

**Comment by dmitry-fedyuk** [comment]
Please update your installation: [github.com/stock2shop/magento2_module_webhook#how-to-update](https://github.com/stock2shop/magento2_module_webhook#how-to-update)

**Comment by vrajeshpatel4u** [comment]
Thank you, Now its working.
