### ISSUE TITLE
When the client tries to update shipping information Magento returns an error Falke Magento 2

### ISSUE THREAD

**Issue by adamcannell** [stock2shop/magento2_module_webhook#6]
CID:152 (Falke)
[Ticket](https://stock2shop.freshdesk.com/a/tickets/19999)

- When the client tries to update shipping information Magento returns an error :
![falke magento](https://user-images.githubusercontent.com/33619255/107384900-106f5780-6afb-11eb-9ae2-74fe8593f607.png)

Magento Developer investigation below:
>I’ve found the area where the routine which forms part of the shipping process fails. It’s in a custom stock2shop module called magento2_module_webhook when it >tries to build up the URL of the product images that makes up an order.
>I have however not identified why it’s not finding the product or why there is a mismatch between the product in the order and the routine resolving the product detail.

Note from @DustinS2S 
>issue does appear to be occurring due to the fact that the products that were on the order were not in Magento, even though the products were recreated this appears to be causing the issue.

**Comment by DustinS2S** [comment]
@adamcannell Bump

**Comment by adamcannell** [comment]
@DustinS2S Why you bumping me?

**Comment by DustinS2S** [comment]
@mannyqi Bump

**Comment by mannyqi** [comment]
I've emailed Surita asking her to do another update on an order so that the error is triggered again.
She should then immediately notify us so we can investigate by looking at the exact error message in the logs.
